import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
// import { useAccount } from 'wagmi';

const Home: NextPage = () => {
  // const [{ data, error, loading }, disconnect] = useAccount({
  //   fetchEns: true,
  // });
  const [showMessage, setShowMessage] = useState<Boolean>(false);

  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-full overflow-hidden">
        <div className="w-full h-full flex flex-col justify-center items-center">
          {showMessage && <h1>Hello World</h1>}
          <div className="w-full flex flex-row justify-center items-center">
            <div
              className="p-8 border border-solid rounded-lg hover:cursor-pointer hover:shadow"
              onClick={() => setShowMessage(!showMessage)}
            >
              <button type="button" className="p-0">
                Click me
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
